### PR TITLE
Adding syntax highlight

### PR DESCRIPTION
**Pull request by byran**
Since we last discussed:

- Syntax highlighting can be toggled on/off without refreshing the page (from the practice details dialog)
- Only one colour theme based on normal cyber-dojo colours

### CODE REVIEW

**Comment by JonJagger** [comment]
Awesome Byran. About to go fishing for the whole day so can't look at it now.
Quick question - what's the default highlighting on or off?

**Comment by byran** [comment]
Default is highlighting off.
Have a fun day fishing.

**Comment by JonJagger** [comment]
Hi Byran,
ran this locally and it's looking good. One thing I noticed though...if I choose C++(g++) and assert then the hiker.tests.cpp file has some of the C++ keywords in green (eg void int) and some of the C++ keywords in purple (eg namespace for). Is this intentional? (I was expecting all keywords to be in the some colour).
Cheers
Jon

**Comment by byran** [comment]
The colour difference is because it's highlighting built in types differently to other keywords. I wouldn't guarantee it makes the same distinction in every language.

It is intentional but not something I chose, it wouldn't be difficult to change.

**Comment by JonJagger** [comment]
I was hoping you'd say that. I'd prefer all keywords in the same colour (eg green). Looks less "busy" that way I think. What do you think?

**Comment by byran** [comment]
I've changed the formatting of built in types for c-like languages so they look like keywords.

**Pull request merged**
